# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Gen storm

on:
  schedule:
    - cron:  '0 0 * * 1'
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 使用别人封装好的的action，用于clone该仓库的源码到工作流中
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f stormlevel/requirements.txt ]; then pip install -r stormlevel/requirements.txt; fi
    - name: 'Gen storm'
      run: python stormlevel/action.py
      
    - name: Add Diff
      run: git add .

    - name: Commit files
      run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "bot fetch stormLevel File" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token:  ${{secrets.TOKEN}}
        branch: main

